name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          # This is required to ensure the `GITHUB_TOKEN` we provide below is
          # **always** used when pushing updates to the changesets release branch.
          # Otherwise the default token will be used, and actions on that versioned
          # release branch will not be triggered.
          persist-credentials: false
      - uses: jdx/mise-action@v4
        with:
          experimental: true
      - run: mise run prepare
      - uses: changesets/action@v1
        with:
          publish: changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_GITHUB_TOKEN }} # noqa
